24-2 4차 정기회의 변경사항 수정 및 테스트 코드 작성
COD3COZY/ReadingFrame-Server pull request #60
Opened 2024-12-17 13:12 UTC by bomzae

## 목적🎯
24-2 4차 정기회의 변경사항 적용

## 변경사항🛠️
- first_review_date 필드 추가
- 책갈피, 메모 등록/수정 시 recentDate 업데이트
- 책갈피 등록/수정 시 markPage 업데이트

## 수행한 테스트✏️
- first_review_date 필드값이 null 값이 아닌지, 오늘을 포함한 과거 날짜를 담는지 테스트
- recentDate 필드값이 수정한 날짜(테스트 날짜)와 같은지 확인
- 책갈피 수정 메서드 호출 시 markPage와 date 값이 변경되는지 mock 데이터를 통한 테스트

## 비고📌
아직 테스트 코드에 대한 이해도가 낮아서.. 수정사항이나 추가사항 있으면 말씀 부탁드립니다 !! (🫶🏻 ' ')

2024-12-17 18:22 UTC, bee-p requested changes
안녕하세요!
테스트 코드 관련해서 컨벤션을 잘 지켜주신 것 같습니다. 감사합니다 :)
몇몇 부분들은 확인 후 수정해주시면 감사하겠습니다.
고생 많으셨습니다🥰

2024-12-17 18:22 UTC, bee-p commented on server/src/test/java/com/codecozy/server/service/BookServiceTest.java
> +    @BeforeEach
`@BeforeEach`를 사용해 테스트 전 데이터들을 따로 구성해주셔서 독립성과 가독성이 모두 좋은 것 같아요😊
그러나 각 테스트들은 독립적으로 수행되어야 하기 때문에, `@AfterEach`를 사용하여 리포지토리의 데이터들을 모두 삭제해주시면 더욱 완벽한 독립성이 유지될 것 같습니다!

그리고 `@BeforeEach`가 붙은 메소드와 `@AfterEach` 메소드 내에서는 단순히 데이터를 세팅해두는 것이기 때문에, 검증을 거치지 않아도 될 것 같습니다..!

또한 이 두 메소드는 맨 위 상단에 작성해주시면 좋을 것 같아요😄

2024-12-17 18:22 UTC, bee-p commented on server/src/test/java/com/codecozy/server/service/BookServiceTest.java
> +
이번 PR에서는 리뷰 작성, 메모 등록, 메모 수정 등의 서비스 내의 로직 코드가 수정된 것으로 이해했습니다!
그래서 해당 서비스 메소드를 호출해서 로직을 수행 후, 
수정한 로직대로 잘 구현이 되었는지 테스트 코드를 작성해보시면 더 좋을 것 같아요🥰

테스트 코드는 '코드를 구현했을 때 그때마다 Postman을 켜서 차례대로 API들을 실행시켜 테스트해야하는 과정' 대신 비교적 빠르고 간편하게 테스트해볼 수 있는 수단이라고 생각해주시면 아마 감이 잡히실 것 같아요..!!

2024-12-19 05:53 UTC, bomzae commented on server/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip
앗 직접적으로 건드린 것은 아닌데, 터미널에서 테스트를 위한 gradle 명령어가 먹히지 않아서 셋팅을 한다는게 버전도 같이 바뀌었네요..!!! 혹시 문제가 된다면 원래대로 변경해서 올려놓겠습니다 !!

2024-12-19 05:55 UTC, bomzae commented on server/src/test/java/com/codecozy/server/service/BookServiceTest.java
> +
빠른 피드백과 눈높이 설명까지 감사합니다!!🤓

2024-12-19 06:07 UTC, bomzae commented on server/src/test/java/com/codecozy/server/service/BookServiceTest.java
> +    @BeforeEach
혹시 @AfterEach 메소드도 상단에 같이 작성하는 이유가 가독성 때문일까요?? @AfterEach 메소드를 하단에 작성하는 경우도 종종 보여서 여쭤봅니다!

2024-12-19 08:20 UTC, bee-p commented on server/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip
아하 빌드 버전이 바뀌면 기존에 작성했던 기능들을 사용 못하거나 하는 일이 발생할 수도 있어서요..!!
오류가 나지 않았다면 다시 복구하지 않아도 될 것 같습니다!
환경 세팅 관련해서는 다같이 적용되는 거라🥲 다음에는 먼저 상의 후 진행 부탁드려요 :D !!

2024-12-19 09:19 UTC, bomzae commented on server/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip
헉 넵 알겠습니다!!

2024-12-19 14:30 UTC, bomzae commented on server/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.11.1-bin.zip
이전에 쓰던 버전으로 복구해도 오류가 발생하지 않네요..!! 혹시나 해서 다시 이전 버전으로 변경해뒀습니다 !!

2024-12-20 01:31 UTC, bee-p approved these changes

2024-12-23 13:41 UTC, merged